### ISSUE TITLE
Use `itemDuration` to add duration

### ISSUE THREAD

**Issue by kazk** [codewars/hspec-formatters-codewars#2]
Hspec `Formatters.V2` has `itemDuration` that can be used to add test case/group duration.

https://www.stackage.org/haddock/lts-20.10/hspec-core-2.9.7/Test-Hspec-Core-Formatters-V2.html#g:2

**Comment by hobovsky** [comment]
Please see #6 .

Known problems:
- HSpec does not report durations of groups. I was able to create a reporter which keeps state between test events (thanks `@dramforever`!), but we need to decide what should be presented in `<COMPLETEDIN::>` of a test group. One proposal is to show a sum of times of its items, but it does not account for surrounding overhead. I thought about storing `startTime` timestamp in `formatterGroupStarted` and calculating its duration in `formatterGroupDone`, but current build setup provides no packages for time manipulation. Let me know which way you prefer, and please add some package for working with time if you want me to use timestamps.
- Crashes originating from outside of `it` result in an incomplete report (see the commented out test case in example test suite). In pessimistic case it can happen that a test run ends with all green and a crash, what can potentially lead to tests erroneously passing.
- I added some test cases to the example test suite to verify presentation of various  test outcomes, but I think it broke your checks. Please let me know if I should revert.

**Comment by kazk** [comment]
Thanks for working on this!

> One proposal is to show a sum of times of its items

I think this is good enough as a start.

> I thought about storing `startTime` timestamp in `formatterGroupStarted` and calculating its duration in `formatterGroupDone`, but current build setup provides no packages for time manipulation.

Can't you just store `Seconds` from [`getRealTime`](https://www.stackage.org/haddock/lts-20.10/hspec-core-2.9.7/Test-Hspec-Core-Formatters-V2.html#v:getRealTime), then get the difference in `formatterGroupDone` by subtracting?

> Crashes originating from outside of `it` result in an incomplete report (see the commented out test case in example test suite). In pessimistic case it can happen that a test run ends with all green and a crash, what can potentially lead to tests erroneously passing.

Is the exit code 0? What happens without our formatter?


> I added some test cases to the example test suite to verify presentation of various test outcomes, but I think it broke your checks. Please let me know if I should revert.

Yeah, the current CI is just there to check it compiles. Ideally, we should have proper tests like in https://github.com/hspec/hspec/blob/55b078e9c4a6143dcb0c9a5ef7faca6d0d788888/hspec-core/test/Test/Hspec/Core/Formatters/V2Spec.hs#L103

You don't need to revert it.

**Comment by hobovsky** [comment]
> Can't you just store `Seconds` from [`getRealTime`](https://www.stackage.org/haddock/lts-20.10/hspec-core-2.9.7/Test-Hspec-Core-Formatters-V2.html#v:getRealTime), then get the difference in `formatterGroupDone` by subtracting?

Uh, I guess I can. I missed it, thanks for pointing it out.


> Is the exit code 0? What happens without our formatter?

I did not check, but I will. But even if return code is error and test run is recognized as failed, all the green and almost no red can be confusing. I hoped to have at least some `<ERROR::>` on crash, but I don't know if I an find a good place to plug into.



> Yeah, the current CI is just there to check it compiles. Ideally, we should have proper tests like in https://github.com/hspec/hspec/blob/55b078e9c4a6143dcb0c9a5ef7faca6d0d788888/hspec-core/test/Test/Hspec/Core/Formatters/V2Spec.hs#L103

I have also two `it`s with QuickCheck tests to see how tests commonly used on CW would look. I did not commit them because they need a dependency to QuickCheck, which is currently not there. Should I commit them? Is it OK to have a dependency to QuickCheck in this project?

**Comment by kazk** [comment]
> Is it OK to have a dependency to QuickCheck in this project?

You can add QuickCheck to `dependencies` under `tests` in `package.yaml`.

**Comment by kazk** [comment]
> But even if return code is error and test run is recognized as failed, all the green and almost no red can be confusing. I hoped to have at least some `<ERROR::>` on crash, but I don't know if I an find a good place to plug into.

I guess the only place is the `main`.

https://github.com/codewars/hspec-formatters-codewars/blob/cd57285fb90dd447bf5c1406f304718ca025b203/test/Main.hs#L9-L10

Call it with [`safeTry`](https://www.stackage.org/haddock/lts-20.10/hspec-core-2.9.7/Test-Hspec-Core-Util.html#v:safeTry) then show `<ERROR::>` on `Left e`?
